### ISSUE TITLE
Colab Notebook Doesnt Work

### ISSUE THREAD

**Issue by jokpreiksa** [mayrf/pkasolver#32]
For some reason Colab notebook doesnt work.

**Comment by wiederm** [comment]
Thanks for raising this issue!
The problem is the pytorch and pyg installation in colabs, it seems that the pip installation is broken. 
We will try to fix this next week! 
In the meantime, you can still build the conda environment locally as specified here: https://github.com/mayrf/pkasolver/blob/main/devtools/conda-envs/test_env.yaml and run the notebook https://github.com/mayrf/pkasolver/blob/main/notebooks/query_example.ipynb

**Comment by nima17** [comment]
Hi @wiederm , I tried running the Colab notebook but I get the following error:

'''RuntimeError: 
object has no attribute sparse_csr_tensor:
  File "/usr/local/lib/python3.8/site-packages/torch_sparse/tensor.py", line 511
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())
    
        return torch.sparse_csr_tensor(rowptr, col, value, self.sizes())
               ~~~~~~~~~~~~~~~~~~'''

**Comment by mayrf** [comment]
This was cause by an outdated version of pytorch. (also discussed here: https://github.com/pytorch/pytorch/issues/74454)
I updated the versions in the notebook and now it should work.
